//! Well-known procedure roots.
//! This file was generated by build.rs.

/// Procedure root of the `RpoFalcon512` authentication component.
pub const RPO_FALCON_512_AUTH: &str =
    "0xaf502aa5c6a6416d3fef0de98b82dada73b066fb6a9c86baa96990f4ab9360bd";
